receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
  awsxray:
    no_verify_ssl: false
    local_mode: false
    region: ${AWS_REGION}
  
  awscloudwatchmetrics:
    region: ${AWS_REGION}
    namespace: FastAPI/OpenTelemetry
    dimension_rollup_option: NoDimensionRollup
    metric_declarations:
      - dimensions: [[service.name], [service.name, service.version]]
        metric_name_selectors:
          - ".*"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [awsxray]
    
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awscloudwatchmetrics]

  extensions: []
